name: task_3_subtitle_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^5.0.0
  http: ^0.13.2
  permission_handler: ^7.0.0
  dio: ^4.0.0
  flutter_downloader: ^1.6.0
  downloads_path_provider: ^0.1.0
  path_provider_ex: ^1.0.1
  folder_picker:
  path_provider: ^2.0.1
  permission: ^0.1.7
  flutter_typeahead: ^3.1.3
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Lobster-Regular
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf